name: 'build-test'

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  test:
    name: tests on ubuntu-latest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # for `native-image-pr-reports` option
    steps:
      - uses: actions/checkout@v3
      - name: Run setup-graalvm action
        uses: ./
        with:
          version: 'dev'
          java-version: '17'
          components: 'native-image'
          set-java-home: 'false'
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build HelloWorld.java with GraalVM Native Image
        run: |
          echo 'public class HelloWorld { public static void main(String[] args) { System.out.println("Hello, World!"); } }' > HelloWorld.java
          javac HelloWorld.java
          native-image -H:+BuildOutputColorful -H:-BuildOutputLinks HelloWorld
          ./helloworld
